=== truongpvk/library-simple-XML/data/books.xsd
<?xml version="1.0"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="library">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="book">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="title"/>
              <xs:element type="xs:string" name="other-title"/>
              <xs:element name="authors">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="author" maxOccurs="unbounded" minOccurs="0"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element type="xs:string" name="description"/>
              <xs:element name="chapters">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="chapter" maxOccurs="unbounded" minOccurs="0">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element type="xs:string" name="chapter-title"/>
                          <xs:element type="xs:string" name="content"/>
                        </xs:sequence>
                        <xs:attribute type="xs:byte" name="id" use="required"/>
                        <xs:attribute type="dateFormat" name="datepublic" use="required"/>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute type="xs:byte" name="total"></xs:attribute>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute type="dateFormat" name="datepublic" use="required"/>
            <xs:attribute type="xs:string" name="bookId" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <!-- Định nghĩa kiểu dữ liệu dateFormat với định dạng mm-dd-yyyy -->
  <xs:simpleType name="dateFormat">
    <xs:restriction base="xs:string">
      <xs:pattern value="(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1])-\d{4}"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== truongpvk/library-simple-XML/data/books.xml
<?xml version='1.0' encoding='utf-8'?>
<library xmlns="http://www.w3schools.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.w3schools.com books.xsd">
	<book bookId="7e4e6abb-1da0-41c3-9b13-6d408787dea9" datepublic="12-07-2024"><title>Tạm Biệt</title><other-title>Goodbye</other-title><authors><author>Nhiều tác giả</author></authors><description>no</description><chapters/></book><book bookId="d8053c15-d4dd-4616-bd2b-ee7e9d0b1828" datepublic="12-07-2024"><title>Xin chào Việt Nam</title><other-title>Hello Vietnam</other-title><authors><author>Nhiều tác giả</author></authors><description>No</description><chapters/></book><book bookId="0bcf89d2-68a2-47ab-aea0-f12ad6537c68" datepublic="12-07-2024"><title>Conan</title><other-title>Thám tử lừng danh Conan</other-title><authors><author>Edogawa</author></authors><description>No</description><chapters/></book></library>
